config/routes.rb
Rails.application.routes.draw do
  root 'episodes#index'
  resources :episodes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/episode.rb
class Episode < ApplicationRecord
  has_one_attached :file
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: %i[ show edit update destroy ]

  # GET /episodes or /episodes.json
  def index
    @episodes = Episode.all
  end

  # GET /episodes/1 or /episodes/1.json
  def show
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
  end

  # POST /episodes or /episodes.json
  def create
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to episode_url(@episode), notice: "Episode was successfully created." }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1 or /episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to episode_url(@episode), notice: "Episode was successfully updated." }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1 or /episodes/1.json
  def destroy
    @episode.destroy

    respond_to do |format|
      format.html { redirect_to episodes_url, notice: "Episode was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def episode_params
      params.require(:episode).permit(:title, :description, :file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_episode.html.erb
<div id="<%= dom_id episode %>" style="margin-top: 20em">
  <p>
    <strong>Title:</strong>
    <%= episode.title %>
  </p>
  <p>
    <strong>File:</strong>
    <%= content_tag(:div, "", data: {
      controller: "podcast",
      podcast_title: episode.title,
      podcast_url: url_for(episode.file)
      # podcast_chapters: episode.chapters.map do |chapter|
      # {
      #   title: chapter.title,
      #   startTime: chapter.start,
      #   endTime: chapter.end
      # } end
    }) %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= episode.description %>
  </p>
</div>

app/views/episodes/_form.html.erb
<%= form_with(model: episode) do |form| %>
  <% if episode.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(episode.errors.count, "error") %> prohibited this episode from being saved:</h2>
      <ul>
        <% episode.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :file, style: "display: block" %>
    <%= form.file_field :file %>
  </div>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing episode</h1>

<%= render "form", episode: @episode %>

<br>

<div>
  <%= link_to "Show this episode", @episode %> |
  <%= link_to "Back to episodes", episodes_path %>
</div>

app/views/episodes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Episodes</h1>

<div id="episodes">
  <% @episodes.each do |episode| %>
    <%= render episode %>
    <p>
      <%= link_to "Show this episode", episode %>
    </p>
  <% end %>
</div>

<%= link_to "New episode", new_episode_path %>

app/views/episodes/new.html.erb
<h1>New episode</h1>

<%= render "form", episode: @episode %>

<br>

<div>
  <%= link_to "Back to episodes", episodes_path %>
</div>

app/views/episodes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @episode %>

<div>
  <%= link_to "Edit this episode", edit_episode_path(@episode) %> |
  <%= link_to "Back to episodes", episodes_path %>

  <%= button_to "Destroy this episode", @episode, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Video</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>